# Generated by Django 4.2.10 on 2024-03-06 08:22

import content.mysite.blocks
import content.mysite.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSite',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('title_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('type', wagtail.blocks.ChoiceBlock(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6')]))])), ('generic_text_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock(required=True))])), ('image_block', wagtail.blocks.StructBlock([('image', content.mysite.blocks.ImageChooserBlock(required=True))]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(content.mysite.models.HeadlessMixin, 'wagtailcore.page'),
        ),
    ]
